// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCssJkTBXs6g5pFem5wRkDrXlX8LuVRDng',
    appId: '1:36315507942:android:06545673d4bab4a70d9f27',
    messagingSenderId: '36315507942',
    projectId: 'fixnear-d5c1c',
    storageBucket: 'fixnear-d5c1c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCryfahAgTNON91WTx2UU6SrkFCZ72mv6w',
    appId: '1:36315507942:ios:a211a15b063184330d9f27',
    messagingSenderId: '36315507942',
    projectId: 'fixnear-d5c1c',
    storageBucket: 'fixnear-d5c1c.firebasestorage.app',
    iosBundleId: 'com.example.fixnear',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCryfahAgTNON91WTx2UU6SrkFCZ72mv6w',
    appId: '1:36315507942:ios:a211a15b063184330d9f27',
    messagingSenderId: '36315507942',
    projectId: 'fixnear-d5c1c',
    storageBucket: 'fixnear-d5c1c.firebasestorage.app',
    iosBundleId: 'com.example.fixnear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2kg2rWZv0akDSAyu6xj80_Q9va2DeGEo',
    appId: '1:36315507942:web:04d8772d80457b740d9f27',
    messagingSenderId: '36315507942',
    projectId: 'fixnear-d5c1c',
    authDomain: 'fixnear-d5c1c.firebaseapp.com',
    storageBucket: 'fixnear-d5c1c.firebasestorage.app',
    measurementId: 'G-KTKWE5G098',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2kg2rWZv0akDSAyu6xj80_Q9va2DeGEo',
    appId: '1:36315507942:web:04d8772d80457b740d9f27',
    messagingSenderId: '36315507942',
    projectId: 'fixnear-d5c1c',
    authDomain: 'fixnear-d5c1c.firebaseapp.com',
    storageBucket: 'fixnear-d5c1c.firebasestorage.app',
    measurementId: 'G-KTKWE5G098',
  );
}
